//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TankkauksetASPNET.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Tankkaus
    {
        public int TankkausId { get; set; }
        [Required(ErrorMessage = "Kirjoita p‰iv‰m‰‰r‰.")]
        public System.DateTime Pvm { get; set; }
        [Required(ErrorMessage = "Kirjoita litrojen m‰‰r‰.")]
        public decimal Litraa { get; set; }
        [Required(ErrorMessage = "Kirjoita litran hinta.")]
        public decimal Euroa { get; set; }
        [Required(ErrorMessage = "Kirjoita rekisterinumero.")]
        public string Reknro { get; set; }
        [Required(ErrorMessage = "Kirjoita mittarilukema.")]
        public int Mittarilukema { get; set; }
        public int Ajomaara { get; set; }
        public Nullable<decimal> Keskikulutus { get; set; }
    }
}
