//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TankkauksetASPNET.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tankkaus
    {
        public int TankkausId { get; set; }
        public System.DateTime Pvm { get; set; }
        public decimal Litraa { get; set; }
        public decimal Euroa { get; set; }
        public string Reknro { get; set; }
        public int Mittarilukema { get; set; }
        public int Ajomaara { get; set; }
        public decimal Keskikulutus { get; set; }
    }
}
